// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMB4Pik0QaFfejeBxI6D_8HytSaa9c64',
    appId: '1:694986775020:web:5ee2829aea53c7edbc88c9',
    messagingSenderId: '694986775020',
    projectId: 'runtrackerapp-b2ba8',
    authDomain: 'runtrackerapp-b2ba8.firebaseapp.com',
    storageBucket: 'runtrackerapp-b2ba8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbfRclIs3yoPwJWHjWylDwhORgRW1dDA',
    appId: '1:694986775020:android:13305b9e4a22a500bc88c9',
    messagingSenderId: '694986775020',
    projectId: 'runtrackerapp-b2ba8',
    storageBucket: 'runtrackerapp-b2ba8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhSyWOJ0gtjp6UFqqtipMnSQOwn5Gb2s',
    appId: '1:694986775020:ios:b678e880c2aba148bc88c9',
    messagingSenderId: '694986775020',
    projectId: 'runtrackerapp-b2ba8',
    storageBucket: 'runtrackerapp-b2ba8.firebasestorage.app',
    iosBundleId: 'com.example.lariYuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOhSyWOJ0gtjp6UFqqtipMnSQOwn5Gb2s',
    appId: '1:694986775020:ios:b678e880c2aba148bc88c9',
    messagingSenderId: '694986775020',
    projectId: 'runtrackerapp-b2ba8',
    storageBucket: 'runtrackerapp-b2ba8.firebasestorage.app',
    iosBundleId: 'com.example.lariYuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBMB4Pik0QaFfejeBxI6D_8HytSaa9c64',
    appId: '1:694986775020:web:ffcc7f8e07bb7297bc88c9',
    messagingSenderId: '694986775020',
    projectId: 'runtrackerapp-b2ba8',
    authDomain: 'runtrackerapp-b2ba8.firebaseapp.com',
    storageBucket: 'runtrackerapp-b2ba8.firebasestorage.app',
  );
}
